[package]
name = "microui-wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
microui = { path = "../microui" }
wgpu = "0.14"
wgpu_glyph = "0.18.0"
winit = "0.27.2"
env_logger = "0.9.0"
pollster = "0.2.5"
bytemuck = "1.12.1"
